### PR TITLE
remove duplicate line

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**
This was so totally worth it's own PR

### CODE REVIEW

**Comment by ryantmer** [comment]
best PR ever. adding test and code review labels.

**Comment by ryantmer** [comment]
nah jk lgtm

**Comment by trevorjonesd2l** [comment]
Should we add any unit tests?

**Comment by ryantmer** [comment]
Good point. Let's get Sauce up and running for this.

**Comment by jstefaniuk-d2l** [comment]
I could test this by using an es6 proxy object to make sure that 'set' is only called once on the property when clear is called

😉

**Pull request merged**
