### PR TITLE
US81632 - Typography auditing

### PR DESCRIPTION
**Pull request by ryantmer**
Turns out a bunch of styles were either being double-applied, not applied, applied in ways that weren't the correct way, or not applied by worked by some random happenstance. These changes remove as much of this uncertainty as possible, by primarily relying on d2l-typography as much as possible, and not modifying those styles unless explicitly required. A lot of small changes here and there, many of which have no visual effect, a few of which have minor visual effects (but these align us to be more consistent with the rest of the LMS, which is using d2l-typography).

See also https://github.com/Brightspace/d2l-search-widget-ui/pull/17 and https://github.com/Brightspace/simple-overlay/pull/2.

### CODE REVIEW

**Comment by trevorjonesd2l** [comment]
Testing:
- [ ] d2l-all-courses
- [ ] d2l-course-tile
- [ ] d2l-filter-menu-content-tabbed
- [ ] d2l-filter-menu-content
- [ ] d2l-list-item-filter
- [ ] d2l-my-courses
- [ ] d2l-search-listbox
- [ ] d2l-search-widget-custom
- [ ] d2l-basic-image-selector
- [ ] d2l-image-selector-tile

**Comment by trevorjonesd2l** [comment]
Should probably get a once over with Bob

**Comment by ryantmer** [comment]
Yeah; I wouldn't be too troubled if this didn't end up in this release tbh.

**Comment by trevorjonesd2l** [comment]
Got Bob's stamp of approval

**Pull request merged**
