### PR TITLE
DE31831: Add a segregated view demo.

### PR DESCRIPTION
**Pull request by njostonehouse**

### CODE REVIEW

**Comment by edwardg8** [comment]
I just added another example to cover the case when there are no courses at all, can revert this if it's not useful.

**Comment by edwardg8** [comment]
Sorry, clicked wrong when submitted the comment. The new added example is useful to me, so I can check if the "View All Courses" link show up or not when there are no courses.

**Comment by njostonehouse** [comment]
The `push` CI is failing with ```**Test run ended in failure: Error thrown outside of test function: Cannot read property '$$' of null**```, not clear why. Will update this branch if I can figure out a fix.

**Comment by njostonehouse** [comment]
I think the `$$` error got introduced in this merge: https://github.com/Brightspace/d2l-my-courses-ui/pull/668

**Comment by edwardg8** [comment]
I think I've seen that error after Polymer3 conversion.

**Pull request closed without merging**
