### PR TITLE
Add in error message langterms now so that they are included in translation

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**

### CODE REVIEW

**Comment by ryantmer** [comment]
Seems good - where are these langterms being used?

**Comment by jstefaniuk-d2l** [comment]
One will be used when the course image catalog is down, the other will be when you try to set an image but it doesn't work

**Comment by jstefaniuk-d2l** [comment]
I just want to include them because I'm sending in the file for translation today and figured that we could save some time this way

**Comment by ryantmer** [comment]
Ohh, gotcha gotcha. So they're not actually in use yet, I was confused. Yep, LGTM!

**Pull request merged**
