### PR TITLE
US78446 - Add grey boxes for before the images load

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**
Follows the "suggested design change" in the story:
https://rally1.rallydev.com/#/51191528503d/detail/userstory/70813306052?fdp=true

### CODE REVIEW

**Comment by CodeBaboon** [comment]
no love for `iron-image`?

**Comment by jstefaniuk-d2l** [comment]
Since we'll be using picturefill, iron-image may now work out in the long run, but it sure does look nice right now

**Comment by jstefaniuk-d2l** [comment]
bleh, sizing broke

**Comment by jstefaniuk-d2l** [comment]
20 is our page size, but this number can really be whatever, as long as it's under the page size but greater than the visible image tiles when you launch the ui

**Comment by jstefaniuk-d2l** [comment]
I'm probably going to put this on hold until https://github.com/Brightspace/d2l-my-courses-ui/pull/167 gets in, since picturefill may change some of this stuff (particularly `iron-image`)

**Comment by jstefaniuk-d2l** [comment]
Iron-image ain't gonna work out ohh well

**Comment by trevorjonesd2l** [comment]
Overall the code looks good. I tested in Chrome, FF, IE and Edge. I couldn't connect to the Mac VM to test Safari though :(

**Comment by trevorjonesd2l** [comment]
K looks good on Chrome and Safari

👍 👍 👍 👍 👍

**Pull request merged**
