### PR TITLE
Add text when no results found

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**
https://rally1.rallydev.com/#/51191528503d/detail/userstory/67510814996

### CODE REVIEW

**Comment by jstefaniuk-d2l** [comment]
@apalaniuk

**Comment by jstefaniuk-d2l** [comment]
@ryantmer

**Comment by apalaniuk** [comment]
LGTM

**Comment by cgalvind2l** [comment]
Change image overlay is broken on IE11, on this branch, and not on master.

`SCRIPT5007: Unable to get property 'bind' of undefined or null reference
File: javascript;charset=utf-8,%22use%20strict%22%3BPolymer(%7Bis%3A%22d2l-my-courses%22%2Cproperties%3A%7BdelayLoad%3A%7Btype%3ABoolean%2Cvalue%3A!1%7D%2CenrollmentsUrl%3AString%2CimageCatalogLocation%3AString%2C_alertMessage%3AString%2C_enrollmentsSearchUrl%3AString%2C_lastEnrollmentsSearchResponse%3AObject%2C_pinnedCoursesMap%3AObject%2C_semestersUrl%3AString%2C_setImageOrg%3AObject%2C_departmentsUrl%3AString%7D%2Cbehaviors%3A%5BPolymer.D2L.MyCourses.CourseTileResponsiveGridBehavior%2CPolymer.D2L.MyCourses.LocalizeBehavior%2CPolymer.D2L.MyCourses.InteractionDetectionBehavior%2CPolymer.D2L.MyCourses.CourseManagementBehavior%5D%2Clisteners%3A%7B%22open-change-image-view%22%3A%22_openChangeImageView%22%7D%2Cready%3Afunction()%7Bthis._pinnedCoursesMap%3D%7B%7D%2Cthis._alertMessage%3Dthis.localize(%22noCoursesMessage%22)%2Cthis.toggleClass(%22hidden%22%2C!0%2Cthis.%24.courseTiles)%2Cthis.toggleClass(%22hidden%22%2C!0%2Cthis.%24.courseList)%3Bvar%20e%3Dthis.%24%24(%22%23all-courses%22)%2Cs%3Dthis.%24%24(%22d2l-all-courses%22)%3Be.focusableNodesOverride%3Ds.focusableNodesOverride.bind(s)%7D%2Cattached%3Afunction()%7Bthis.delayLoad%7C%7Cthis.%24.enrollmentsRootRequest.generateRequest()%2Cthis.%24%24(%22iron-scroll-threshold%22).scrollTarget%3Dthis.%24%5B%22all-courses%22%5D.scrollRegion%7D%2CgetCourseTileItemCount%3Afunction()%7Breturn%20this.pinnedEnrollments.length%7D%2C_onEnrollmentsRootResponse%3Afunction(e)%7Bif(200%3D%3D%3De.detail.status)%7Bvar%20s%3Ddocument.createElement(%22d2l-siren-parser%22)%2Cn%3Ds.parse(e.detail.xhr.response)%3Bif(!n.hasAction(%22search-my-enrollments%22))return%3Bvar%20t%3Dn.getActionByName(%22search-my-enrollments%22)%2Ci%3D%7BpageSize%3A25%2CembedDepth%3A1%2CsortField%3A%22pinDate%22%2CsortDescending%3A!0%7D%3Bthis._enrollmentsSearchUrl%3Dthis.createActionUrl(t%2Ci)%2Cthis.%24.enrollmentsSearchRequest.generateRequest()%7Delse%20this._showContent()%7D%2C_onEnrollmentsSearchResponse%3Afunction(e)%7Bif(200%3D%3D%3De.detail.status)%7Bvar%20s%3Ddocument.createElement(%22d2l-siren-parser%22)%2Cn%3Ds.parse(e.detail.xhr.response)%2Ct%3Dn.getSubEntitiesByClass(%22enrollment%22)%2Ci%3D%5B%5D%2Cl%3D%5B%5D%3Bt.forEach(function(e)%7Bif(e.hasClass(%22pinned%22))%7Bvar%20s%3Dthis.getEnrollmentIdentifier(e)%3Bthis._pinnedCoursesMap.hasOwnProperty(s)%7C%7C(i.push(e)%2Cthis._pinnedCoursesMap%5Bs%5D%3D!0)%7Delse%20l.push(e)%7D%2Cthis)%2Cthis.pinnedEnrollments%3Dthis.pinnedEnrollments.concat(i)%2Cthis.unpinnedEnrollments%3Dthis.unpinnedEnrollments.concat(l)%2Cthis.notifySplices(%22pinnedEnrollments%22%2C%5B%7Bindex%3Athis.pinnedEnrollments.length-i.length%2Cremoved%3A%5B%5D%2CaddedCount%3Ai.length%2Cobject%3Athis.pinnedEnrollments%2Ctype%3A%22splice%22%7D%5D)%2Cthis.notifySplices(%22unpinnedEnrollments%22%2C%5B%7Bindex%3Athis.unpinnedEnrollments.length-l.length%2Cremoved%3A%5B%5D%2CaddedCount%3Al.length%2Cobject%3Athis.unpinnedEnrollments%2Ctype%3A%22splice%22%7D%5D)%2Cthis.set(%22enrollments%22%2Ct)%2Cthis._hasPinnedEnrollments%3Dthis.pinnedEnrollments.length%3E0%2Cthis._hasEnrollments%3Dthis._hasPinnedEnrollments%7C%7Cthis.unpinnedEnrollments.length%3E0%2Cthis._hasEnrollments%26%26(this._alertMessage%3Dthis.localize(%22noPinnedCoursesMessage%22))%2Cthis.fire(%22recalculate-columns%22)%7Dthis.toggleClass(%22hidden%22%2C!0%2Cthis.%24.lazyLoadSpinner)%2Cthis.%24%24(%22iron-scroll-threshold%22).clearTriggers()%2Cthis._showContent()%7D%2C_openChangeImageView%3Afunction(e)%7Bvar%20s%3Dthis.%24%24(%22%23basic-image-selector-overlay%22)%2Cn%3Dthis.%24%24(%22d2l-basic-image-selector%22)%3Be.detail.organization%26%26(this._setImageOrg%3De.detail.organization)%2Cs.focusableNodesOverride%3Dn.focusableNodesOverride.bind(n)%2Cthis.%24%24(%22%23basic-image-selector-overlay%22).open()%7D%2C_openAllCoursesView%3Afunction(e)%7Be.preventDefault()%2Ce.stopPropagation()%2Cthis.%24%24(%22%23all-courses%22).open()%2Cthis.%24%24(%22d2l-all-courses%22).loadCourseTiles()%2CsetTimeout(function()%7Bthis.fire(%22recalculate-columns%22)%7D.bind(this)%2C50)%7D%2C_refreshPage%3Afunction()%7Bdocument.location.reload(!0)%7D%2C_showContent%3Afunction()%7Bthis.toggleClass(%22hidden%22%2C!0%2Cthis.%24.initialLoadingSpinner)%2Cthis.toggleClass(%22hidden%22%2C!1%2Cthis.%24%24(%22.my-courses-content%22))%7D%2C_loadNextEnrollmentsPage%3Afunction()%7Bif(this.%24%5B%22all-courses%22%5D.opened%26%26this._lastEnrollmentsSearchResponse)%7Bvar%20e%3Ddocument.createElement(%22d2l-siren-parser%22)%2Cs%3De.parse(this._lastEnrollmentsSearchResponse)%3Bs.hasLink(%22next%22)%26%26(this._enrollmentsSearchUrl%3Ds.getLinkByRel(%22next%22).href%2Cthis.%24.enrollmentsSearchRequest.generateRequest()%2Cthis.toggleClass(%22hidden%22%2C!1%2Cthis.%24.lazyLoadSpinner))%7D%7D%7D)%0A%2F%2F%23%20sourceURL%3Dhttp%3A%2F%2F127.0.0.1%3A8080%2Fd2l-my-courses.html-46.js%0A, Line: 1, Column: 2999`

**Comment by cgalvind2l** [comment]
Unsure of the scope of this story, but what if the request to the service straight-up fails? e.g. if I change the course-image-catalog endpoint config variable to something that doesn't exist, the search request naturally fails but I just see a blank page.

**Comment by jstefaniuk-d2l** [comment]
We have very little error handling anywhere for the image ui at the moment, so I'm going to say out of scope until next week

I assume that the `No connection` dialog will be the same for launching the ui and searching (I'll ask Bob tomorrow)

**Comment by jstefaniuk-d2l** [comment]
- [ ] Look into the IE error

**Comment by jstefaniuk-d2l** [comment]
So I think my recent merge fixed it, there's still some strangeness in IE:

image

but I think that's a fix for the `d2l-navigation-ui` and not this PR

**Comment by ryantmer** [comment]
@jstefaniuk-d2l That extra X is a thing that IE adds to all input fields, it's... kinda nice, but also kinda dumb. Might be able to disable it, idk =/

**Comment by jstefaniuk-d2l** [comment]
@ryantmer 
I wonder if there's a way to hook into that X and use it as our X

**Comment by jstefaniuk-d2l** [comment]
Looks like we can just clear it, I'll make a PR

http://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs

**Comment by jstefaniuk-d2l** [comment]
@cgalvind2l can you try it again and see if the error shows up for you?

**Comment by cgalvind2l** [comment]
Yup, this is on my list to test after lunch (I was away all morning in a training session)

**Comment by cgalvind2l** [comment]
It's working now on IE.

**Comment by cgalvind2l** [comment]
Issue: really long search terms only getting broken onto different lines when a space happens.

**Comment by jstefaniuk-d2l** [comment]
Cool, I'll fix that as soon as I get a chance

**Comment by cgalvind2l** [comment]
Issue: symbols.

2016-10-13 13_46_57-homepage - dev

**Comment by jstefaniuk-d2l** [comment]
I think that's an issue with the `d2l-search-widget-ui`, I was able to get it to add querystrings as well

**Comment by cgalvind2l** [comment]
Where can we submit that as a defect?

**Comment by jstefaniuk-d2l** [comment]
https://github.com/Brightspace/d2l-search-widget-ui

**Comment by ryantmer** [comment]
There... may or may not be any sanitization on that.

(There isn't.)

I'll create an issue in the repo (which is [here](https://github.com/Brightspace/d2l-search-widget-ui), for future reference).

**Comment by ryantmer** [comment]
Oh, wait - I think the correct answer here would actually be to URI-encode the search string. The WC itself probably shouldn't do any sanitization since it's not up to it to be aware what safe input for the given Action would be.

**Comment by jstefaniuk-d2l** [comment]
You type the search string into the wc and hit enter, this code only really handles the response

**Comment by ryantmer** [comment]
https://github.com/Brightspace/d2l-search-widget-ui/releases/tag/v0.0.15 has been released, which URI-encodes the given search string! 🎉

**Comment by jstefaniuk-d2l** [comment]
Everything breaks when you update BSI, putting in a fix for that here as well

**Comment by jstefaniuk-d2l** [comment]
rebase destroyed everything yarg

**Comment by jstefaniuk-d2l** [comment]
Anyone want to test this?

**Comment by cgalvind2l** [comment]
I totally would except that my VirtualBox is broken and I can't figure out how to fix it :(

**Comment by CodeBaboon** [comment]
I will test

**Comment by jstefaniuk-d2l** [comment]
Having the close button wipe out the search is going to require a bit more looking into, may break that into another PR

**Comment by ryantmer** [comment]
@jstefaniuk-d2l Yeah, the course search field doesn't do it either anyway =.

**Comment by CodeBaboon** [comment]
LGTM

**Comment by jstefaniuk-d2l** [comment]
Merging once CI goes

**Pull request merged**
