### PR TITLE
added new PR process information

### PR DESCRIPTION
**Pull request by cgalvind2l**
AC: the process for testing that we discussed during retro is made clear in the README
Areas of risk: oh geez none I hope

### CODE REVIEW

**Comment by CodeBaboon** [comment]
I don't see a US# :p

**Comment by cgalvind2l** [comment]
Ummm you'll note that the documentation says IF APPLICABLE.

**Comment by ryantmer** [comment]
I like the level of sass in this PR.

**Comment by CodeBaboon** [comment]
Should we indicate that when testing a PR there should be detailed test steps and that those should be reviewed before being merged? Or is that a separate PR?

**Comment by cgalvind2l** [comment]
I was unsure what level of detail to put in the README for the repo; I was thinking not to put the entire process in (as that is team specific rather than codeline specific). But I think that adding the bit about test steps and reviewing them is probably a good idea.

**Comment by CodeBaboon** [comment]
Docs LLTM. Tested with the following steps:

- used eyeballs to read words
- used mindballs to comprehend words
- used memoryballs to crossreference with earlier discussion
- used wordballs to discuss gaps with developer
- used thumbballs to type results here

**Comment by cgalvind2l** [comment]
Wow, that's way more balls than I would typically expect to be involved in a PR.

I have evaluated your test plan for gaps and have found that they were all filled with balls. So should be good. Just need someone to approve so it can be merged...

**Pull request merged**
