### PR TITLE
Rearrange layout

### PR DESCRIPTION
**Pull request by ryantmer**
No US for this (since I forgot to make one), but the latest designs move the search field into the all courses overlay, and ditch the tabbed layout. Could almost just revert the commits where I added the tabbed layout, but meh, still had to move the search field anyway.

### CODE REVIEW

**Comment by apalaniuk** [comment]
@ryantmer Mayhaps the [.button-bar](https://github.com/Brightspace/d2l-my-courses-ui/blob/4aad9bd1a64ec0e7d9eefd0bf9d8ec253c9c92d3/d2l-my-courses.html#L52) through to the [.view-button](https://github.com/Brightspace/d2l-my-courses-ui/blob/4aad9bd1a64ec0e7d9eefd0bf9d8ec253c9c92d3/d2l-my-courses.html#L79) styles can be removed as well?

**Comment by ryantmer** [comment]
@apalaniuk Ah, good catch. Will do!

**Comment by apalaniuk** [comment]
A couple more unused things (I'm scraping the bottom of the barrel now, so I think this is it):

[`_hasManyEnrollments`](https://github.com/Brightspace/d2l-my-courses-ui/blob/rearrange-layout/d2l-course-management-behavior.html#L108)
[Tab localization entries](https://github.com/Brightspace/d2l-my-courses-ui/blob/rearrange-layout/localize-behavior.html#L59)

**Comment by ryantmer** [comment]
I guess I really should have looked more closely at the PR when I merged this... haha, thanks!

**Comment by apalaniuk** [comment]
LGTM! :+1:

**Pull request merged**
