### PR TITLE
DE24228 - Fix #272 (dropdown console errors)

### LINKED ISSUE #272: DE24228 - Console errors related to custom dropdown
Several console errors exist due to the dropdown behavior expecting elements in `d2l-dropdown-content` to exist, which don't in our custom dropdown component. Adding these elements results in undesired behavior as we'll lose control of width styling.

- Clearing search, or clicking into empty search bar, or doing various searches:

`    Uncaught TypeError: Cannot read property 'style' of null
    at HTMLElement.__position (shared.html:9547)
    at HTMLElement.<anonymous> (shared.html:9414)
    at HTMLElement.__openedChanged (shared.html:9436)
    at HTMLElement._observerEffect (shared.html:4535)
    at HTMLElement._effectEffects (shared.html:4380)
    at HTMLElement._propertySetter (shared.html:4364)
    at HTMLElement.setter (shared.html:4443)
    at HTMLElement.open (shared.html:9277)
    at HTMLElement._onElementFocus (d2l-my-courses.html:11059)
    at HTMLButtonElement.handler (shared.html:3439)`
    
- Clicking into the empty search bar on first opening of the overlay:
  
`   Uncaught TypeError: Cannot read property 'render' of null
    at HTMLElement.forceRender (shared.html:9284)
    at HTMLElement.__openedChanged (shared.html:9433)
    at HTMLElement._observerEffect (shared.html:4535)
    at HTMLElement._effectEffects (shared.html:4380)
    at HTMLElement._propertySetter (shared.html:4364)
    at HTMLElement.setter (shared.html:4443)
    at HTMLElement.open (shared.html:9277)
    at HTMLElement._onElementFocus (d2l-my-courses.html:11059)
    at HTMLInputElement.handler (shared.html:3439)`

### PR DESCRIPTION
**Pull request by ryantmer**
Fixes #272.

The crux of the console errors we were seeing was that the d2l-search-dropdown-content was not quite exactly the same as d2l-dropdown-content, while still using the DropdownContentBehavior. There really wasn't much benefit to d2l-search-dropdown-content anyway, so it's been removed, and the console errors are no more.

Also, switch the Polymer-2.0-friendly "slot" while we're here.

Also also, did some changes to visual consistency so that the live search dropdown matches the Sort By dropdown formatting in terms of text and style (confirmed with Bob that this is the correct approach).

Also also also, added a call to `_updateIcon()` as selecting an item in the live search list would result in a situation where the results couldn't be cleared.

Also also also also, fixed a couple little things in the recent courses list behaviour. Previously, this was only being updated in local storage, so you had to refresh the page to get your actually-most-recent searches. Now, they are always up to date - type something in, either click an item in the live search or hit enter, and whatever was in the search field is added to recent searches right away.

### CODE REVIEW

**Comment by JoshuaKlassen** [comment]
Testing notes:

---
Testing plan:
- open View All Courses
- check console for errors
- check if live search dropdown looks like the Sort By dropdown
- search and see if search goes into the live search dropdown

---
Tested on:
- [ ] Chrome

- [ ] FireFox

- [ ] Internet Explorer

- [ ] Edge

- [ ] Safari

- [ ] iOS

- [ ] Android

**Comment by JoshuaKlassen** [comment]
Finished testing
I found a few things, however, they aren't related to this PR specifically, since it was to stop the console errors, which it does!

**Comment by ryantmer** [comment]
Updated! Looks like the three issues you mentioned (entering spaces, recent searches not showing again, and the dropdown not going away when you leave the field) are all fixed :dancer: As for the "Featured Searches" text, I checked Bob but no response yet - I don't think it's super high importance either way, so I think this is good to go!

**Comment by JoshuaKlassen** [comment]
LGTM

**Pull request merged**
