### PR TITLE
US101469: Stop testing Firefox on Sauce, in case automated test flake…

### PR DESCRIPTION
**Pull request by njostonehouse**
…s are restricted to that browser.

### CODE REVIEW

**Comment by njostonehouse** [comment]
This still seems flaky, although other bits are failing. Although Firefox seems to be especially bad at failing, the other browsers seem to get tripped up from time to time too (in new and exciting ways!)

**Comment by m6jones** [comment]
I think the tests need to be redesigned and the wall of text might actually be a problem with `d2l-tabs` or the way we use it. Dragon Slayer that isn't taken over by My Courses.

**Comment by njostonehouse** [comment]
I'm trying a few different things as experiments. Here's the next one: https://github.com/Brightspace/d2l-my-courses-ui/pull/631 (it didn't work).

**Comment by svanherk** [comment]
Closing, the original issue with that Firefox-only flake was solved by moving to Polymer 3

**Pull request closed without merging**
