### PR TITLE
Update to latest d2l-dropdown and d2l-menu.  

### PR DESCRIPTION
**Pull request by dbatiste**
Updating "select" event accordingly.

### CODE REVIEW

**Comment by dbatiste** [comment]
fyi: @jstefaniuk-d2l , @apalaniuk , @ryantmer : 

The `select` event name changed for the `d2l-menu` component.  This was the only spot I found that needed updating.  Let me know if you think there should be others.

**Comment by ryantmer** [comment]
Yep, LGTM - we're not using a lot of `d2l-menu` directly :)

**Comment by ryantmer** [comment]
@dbatiste mind if I merge this? We're lagging behind in `d2l-menu` versions in particular, causing BSI version bummers.

**Comment by dbatiste** [comment]
go for it.  `d2l-navigation` has a similar PR that will need to be merged before updating BSI since this is breaking change.

**Pull request merged**
