### PR TITLE
Fix node 10 travis problem

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**

### CODE REVIEW

**Comment by ryantmer** [comment]
What happens with node 10? Would be good to capture that in the commit as well :octocat:

**Comment by jstefaniuk-d2l** [comment]
It spits out the error: `TypeError: Cannot read property '1' of null`

**Comment by jstefaniuk-d2l** [comment]
image

**Comment by svanherk** [comment]
I did re-run it and it failed again, different timeout this time.  Trying again

**Pull request merged**
