### PR TITLE
s

### PR DESCRIPTION
**Pull request by ryantmer**
_s_

### CODE REVIEW

**Comment by jstefaniuk-d2l** [comment]
:+1:

**Comment by jstefaniuk-d2l** [comment]
Seems to destroy everything XD

**Comment by ryantmer** [comment]
_hahahaha wtf_ how did this fail CI?

**Comment by trevorjonesd2l** [comment]
*Smooth*

**Comment by jstefaniuk-d2l** [comment]
👎 On second thought, too risky

**Comment by ryantmer** [comment]
hokay fixed by https://github.com/Brightspace/d2l-my-courses-ui/pull/220 i merg now

**Pull request merged**
