### PR TITLE
replace option element with div and role

### LINKED ISSUE #104: Safari does not display previous search terms
In Chrome or Firefox when I click into the search list box I see a list of previously searched terms:

recent-searches-chrome

However in Safari the terms do not appear:

recent-searches-safari

Looking into the source, the terms are being stored/retrieved and inserted into the document, so that is not an issue. It appears to be related to how Safari handles the `<option>` element. Note that in Chrome the user agent stylesheet sets `display: block`, as seen here:

option-element-chrome

However in Safari not only does the user agent stylesheet not set the display, the browser actively refuses to respect the setting that is being applied by the Daylight CSS (note that it is lightly greyed out and struck-through):

option-element-safari

Even if I apply `display: block` directly to the element Safari will strike it out and not show the element.

### PR DESCRIPTION
**Pull request by CodeBaboon**
This is to fix #104.

### CODE REVIEW

**Comment by apalaniuk** [comment]
Ah, I just put this in my other PR as well.

**Comment by CodeBaboon** [comment]
@apalaniuk  We can kill this one if you prefer, doesn't matter to me.

**Comment by apalaniuk** [comment]
Nah it's fine, this will be less confusing. I'll revert my change since it conflicts.

Thanks!

**Comment by ryantmer** [comment]
In FF on Windows, this PR does fix the formatting (padding, mostly) of the recent searches, but I still can't up/down to select things. I presume that's a separate issue, though - if so, then LGTM!

**Comment by CodeBaboon** [comment]
So this PR is actually breaking the up/down to select things on Chrome. I did not know that was a thing. So we can either address that whole issue across all browsers here before we break it on Chrome, or we can break it and then fix it for everyone in a different PR. Thoughts?

**Comment by ryantmer** [comment]
I'm in the "fix first" camp, otherwise we'd be looking at a regression :cry:

**Comment by apalaniuk** [comment]
@CodeBaboon  https://github.com/Brightspace/d2l-my-courses-ui/blob/master/d2l-search-listbox.html#L95

**Comment by apalaniuk** [comment]
:+1:

**Pull request merged**
